default: &default
  adapter: mysql2
  encoding: utf8
  database: loveua
  username: root
  password: root
  host: localhost
  port: 3306
  secure_auth: false

development:
  <<: *default


test: &test
  <<: *default
  database: loveua_test

production:
  <<: *default

cucumber:
  <<: *test